KS-2-5 calculation and outputting compound interest
Asplet/KotlinSprint pull request #10
Opened 2024-11-14 22:02 UTC by Asplet

Насколько я понял возведение в степень в языке возможна только посредством функции pow библиотеки math, верно?
Задачи со звёздочкой - хороший ход, заставляет покопаться "наперёд", появляется азарт и интерес, спасибо!

2024-11-15 19:40 UTC, ievetrovdev requested changes

2024-11-15 19:40 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task5.kt
> +    val totalDeposit = String.format("%.3f", (deposit * (1 + interestRate / 100).pow(yearsOfDeposit)))
Код корректный, но давай здесь делать только вычисление, предполагая, что результат может идти дальше на сервер, а форматировать будем непосредственно при выводе в консоль

К тому же, давай вынесем 100 и 1 в переменные так как это [магические числа](https://ru.wikipedia.org/wiki/Магическое_число_(программирование)#Плохая_практика_программирования), что тоже не очень хорошо

2024-11-15 21:25 UTC, Asplet commented on src/main/kotlin/lesson_2/lesson2_task5.kt
> +    val totalDeposit = String.format("%.3f", (deposit * (1 + interestRate / 100).pow(yearsOfDeposit)))
Добавил несколько переменных, чтобы формула больше соответствовала действительности. Вынес форматирование в println() (Тут удачно легло просмотренное видео из третьего урока про вывод выражений в фигурных скобках)

2024-11-16 12:29 UTC, ievetrovdev approved these changes
Теперь все верно!

2024-11-16 12:51 UTC, merged