KS-1-3 Gagarin's fly time
Asplet/KotlinSprint pull request #3
Opened 2024-11-13 22:49 UTC by Asplet

2024-11-13 23:23 UTC, ievetrovdev requested changes
Я оставил комментарий для доработки. чтобы правильно залить изменения, надо:
 - переключиться в Идее на нужную ветку
 - внести изменения и сделать коммит в эту ветку (следить чтобы в стейдж не добавились лишние задачи, которые не относятся к данной задаче)
 - отправить ссылку в бот на этот же пулл реквест к соответствующей задаче

2024-11-13 23:23 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task3.kt
> +    println("0" + minute)
Добавлять 0 для корректного вывода не лучшее решение по стилю и функционалу. Есть еще идеи, как избежать хардкода нуля?)

2024-11-14 09:06 UTC, Asplet commented
Сначала не придумалось ничего, кроме как задать переменные как строки, чтобы выводился результат с нулём перед часом и минутой. Запушил так. Однако, в процессе работы над 5-й задачей, обнаружилось, что там так не сработает, и прошерстив немного обнаружил "String.format()". Поэтому и переделал третью задачу под это и запушил ещё раз.

2024-11-14 20:18 UTC, ievetrovdev approved these changes
Молодец, очень верный подход!

Теперь эту ветку можно мержить в мастер. напомню, перед созданием новой ветки надо переключиться в мастер, обновить его (чтобы слитые изменения прилетели в локальный проект) и только тогда бранчиться

2024-11-14 20:44 UTC, merged